services:
  git-web:
    container_name: git-web
    image: ghcr.io/bobgregory/websites:latest
    restart: unless-stopped
    deploy:
      labels:
        com.ouroboros.enable: "true"

  updater:
    image: gmt2001/ouroboros:latest
    container_name: updater
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json:ro
    environment:
        - INTERVAL=300
        - CLEANUP=true
        - LOG_LEVEL=info
        - SELF_UPDATE=false
        - LABEL_ENABLE=true
        - LABELS_ONLY=true